language: scala
scala:
  - "2.11.8"
  - "2.12.0"
jdk:
  - oraclejdk8
# - openjdk8

script: "sbt ++$TRAVIS_SCALA_VERSION clean coverage test"
after_success: "sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls"
